name: Publish deb package

on:
  push:
    branches:
      master

jobs:
  create_release:
    runs-on: panda-arc
    
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      v-version: ${{ steps.version.outputs.v-version }}
    
    steps:
      - name: Install git
        run: sudo apt-get -qq update -y && sudo apt-get -qq install git curl jq -y
      
      - name: Get next version
        uses: reecetech/version-increment@2023.10.2
        id: version
        with:
          release_branch: master
          use_api: true

  build_deb_2004:
    needs: create_release
    runs-on: ubuntu-20.04

    steps:
      - name: Install git
        run: sudo apt-get -qq update -y && sudo apt-get -qq install cmake ninja-build rapidjson-dev -y

      - name: Check out
        uses: actions/checkout@v4

      - name: Build package
        working-directory: .
        run: mkdir build && cd build && cmake -GNinja .. && ninja && ninja package

      - name: Rename .deb file
        run: mv build/libosi-0.1.1-Linux.deb build/libosi_20.04.deb

      - name: Upload debian package to release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.create_release.outputs.v-version }}
          files: |
            build/*.deb

  build_deb_2204:
    needs: create_release
    runs-on: ubuntu-22.04

    steps:
      - name: Install git
        run: sudo apt-get -qq update -y && sudo apt-get -qq install cmake ninja-build rapidjson-dev -y

      - name: Check out
        uses: actions/checkout@v4

      - name: Build package
        working-directory: .
        run: mkdir build && cd build && cmake -GNinja .. && ninja && ninja package

      - name: Rename .deb file
        run: mv build/libosi-0.1.1-Linux.deb build/libosi_22.04.deb

      - name: Upload debian package to release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.create_release.outputs.v-version }}
          files: |
            build/*.deb